---
# Cleaning the Dataset
---

### Dataset Cleaning Process

This notebook demonstrates the data cleaning process for the `mtcars2.csv` dataset, which contains information about various car models and their specifications.

#### Data Loading and Initial Processing
- The dataset is imported using pandas and stored in a DataFrame called `cars`
- The first unnamed column was renamed to 'model' to better reflect its content
- The 'S.No' column was removed as it was likely just an index column that isn't needed for analysis

#### Data Cleaning Operations
- Missing values in the 'qsec' column (quarter-mile time) were filled with the mean value of that column
- The 'qsec' column was converted to numeric format using `pd.to_numeric()` with 'coerce' option to handle any non-numeric values
- The 'mpg' (miles per gallon) column was converted to float data type for proper numerical processing

#### Data Analysis
- A correlation matrix was created to understand relationships between numerical variables
- This correlation matrix (stored in `df`) helps identify which features are strongly correlated with each other
- For example, there are strong negative correlations between 'mpg' and both 'cyl' (cylinders) and 'wt' (weight)

#### Dataset Structure
- The dataset contains 32 car models with 12 features including:
    - Model name (labeled as 'Unnamed: 1')
    - Performance metrics (mpg, qsec)
    - Engine specifications (cyl, disp, hp, carb)
    - Physical attributes (wt)
    - Technical specifications (drat, vs, am, gear)
- All columns except the model name are numerical, with a mix of float and integer data types

This cleaning process ensures the dataset is ready for further analysis or modeling by addressing missing values, proper data typing, and removing unnecessary columns.

---

In [ ]:
import pandas as pd # importing pandas

In [ ]:
cars = pd.read_csv("mtcars2.csv")         # reading the csv file
cars = cars.rename(columns={'Unnamed : 1':'model'}) # renaming the first column
cars

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
cars.qsec = cars.qsec.fillna(cars.qsec.mean) # fill missing values in qsec with the mean of qsec
cars

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,<bound method Series.mean of 0 16.46\n1 ...,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.0,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.9,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.3,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.9,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.4,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.6,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.0,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,<bound method Series.mean of 0 16.46\n1 ...,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.9,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.3,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,<bound method Series.mean of 0 16.46\n1 ...,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.7,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [ ]:
cars = cars.drop(columns=["S.No"]) # Drop the first column
cars

,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,<bound method Series.mean of 0 16.46\n1 ...,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.0,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.9,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.3,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.9,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.4,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.6,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.0,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,<bound method Series.mean of 0 16.46\n1 ...,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.9,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.3,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,<bound method Series.mean of 0 16.46\n1 ...,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.7,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [ ]:
cars.qsec = pd.to_numeric(cars.qsec, errors='coerce')   # convert to numeric
# Fill missing values in 'qsec' with the mean of the column    
cars.qsec = cars.qsec.fillna(cars.qsec.mean())          

# Then calculate the correlation matrix
df = cars[['mpg','cyl','disp','hp','drat','wt','qsec','vs','am','gear','carb']].corr()
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
mpg,1.000000,-0.852162,-0.847551,-0.776168,0.681172,-0.867659,0.360351,0.664039,0.599832,0.480285,-0.550925
cyl,-0.852162,1.000000,0.902033,0.832447,-0.699938,0.782496,-0.548775,-0.810812,-0.522607,-0.492687,0.526988
disp,-0.847551,0.902033,1.000000,0.790949,-0.710214,0.887980,-0.385207,-0.710416,-0.591227,-0.555569,0.394977
hp,-0.776168,0.832447,0.790949,1.000000,-0.448759,0.658748,-0.650674,-0.723097,-0.243204,-0.125704,0.749812
drat,0.681172,-0.699938,-0.710214,-0.448759,1.000000,-0.712441,0.120175,0.440278,0.712711,0.699610,-0.090790
wt,-0.867659,0.782496,0.887980,0.658748,-0.712441,1.000000,-0.130362,-0.554916,-0.692495,-0.583287,0.427606
qsec,0.360351,-0.548775,-0.385207,-0.650674,0.120175,-0.130362,1.000000,0.667873,-0.271763,-0.203784,-0.573987
vs,0.664039,-0.810812,-0.710416,-0.723097,0.440278,-0.554916,0.667873,1.000000,0.168345,0.206023,-0.569607
am,0.599832,-0.522607,-0.591227,-0.243204,0.712711,-0.692495,-0.271763,0.168345,1.000000,0.794059,0.057534
gear,0.480285,-0.492687,-0.555569,-0.125704,0.699610,-0.583287,-0.203784,0.206023,0.794059,1.000000,0.274073
carb,-0.550925,0.526988,0.394977,0.749812,-0.090790,0.427606,-0.573987,-0.569607,0.057534,0.274073,1.000000

In [ ]:
cars.mpg = cars.mpg.astype(float)   # convert to float  
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 1  32 non-null     object
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64
 9   am          32 non-null     int64
 10  gear        32 non-null     int64
 11  carb        32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

---